### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mmc1718** [mmc1718/wikigeo#7]
getting data ('NANT Y GRAEN A NANT GANOL', 52.864636479, -3.861978822)
Traceback (most recent call last):
  File "c:\Users\marym\Documents\GitHub\etl\wikitablescript.py", line 207, in <module>
    run()
  File "c:\Users\marym\Documents\GitHub\etl\wikitablescript.py", line 169, in run
    wikidata = run_page_search(wiki, searches)
  File "c:\Users\marym\Documents\GitHub\etl\wikitablescript.py", line 56, in run_page_search
    response = wikiobj.get_page_match(param[0], param[1], param[2], bestmatch='name', minnamematch=50)
  File "C:\Users\marym\anaconda3\envs\geo2\lib\site-packages\wikigeo\wikisearch.py", line 183, in get_page_match
    for page, info in search_results['query']['pages'].items():
KeyError: 'query'

**Comment by mmc1718** [comment]
Updated, needs reuploading

**Comment by mmc1718** [comment]
There was no 'query', think this is an inconsistency in how the wikiapi responds. Updated (next time refer to line with commit..)
